# Generated by Django 3.1 on 2020-08-14 22:41

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('image', stdimage.models.StdImageField(upload_to='enemies', verbose_name='Image')),
                ('facebook_icon', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('twitter_icon', models.CharField(default='#', max_length=100, verbose_name='Twitter')),
                ('instagram_icon', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Enemy',
                'verbose_name_plural': 'Enemies',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('icon', models.CharField(choices=[('lni-rocket', 'Rocket'), ('lni-laptop-phone', 'Laptop'), ('lni-cog', 'Cog'), ('lni-leaf', 'Leaf'), ('lni-layers', 'Layers')], max_length=20, verbose_name='Icon')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
                ('image', stdimage.models.StdImageField(upload_to='heroes', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='OtherImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', stdimage.models.StdImageField(upload_to='other_images', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Other Image',
                'verbose_name_plural': 'Other Images',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('icon', models.CharField(choices=[('lni-package', 'Package'), ('lni-drop', 'Drop'), ('lni-star', 'Star')], max_length=15, verbose_name='Icon')),
                ('price', models.CharField(max_length=4, verbose_name='Price')),
                ('title', models.CharField(max_length=10, verbose_name='Title')),
                ('users', models.CharField(max_length=20, verbose_name='Users')),
                ('storage', models.CharField(max_length=70, verbose_name='Storage')),
                ('support', models.CharField(max_length=50, verbose_name='Support')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('status', models.CharField(max_length=30, verbose_name='Status')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('image', stdimage.models.StdImageField(upload_to='testimonials', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
